// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN4G_eenl95cZIQL2Uc2mvRTz6eNQuhAI',
    appId: '1:9980413148:web:3f6201f6d7d709951a6019',
    messagingSenderId: '9980413148',
    projectId: 'protectora-555d4',
    authDomain: 'protectora-555d4.firebaseapp.com',
    storageBucket: 'protectora-555d4.appspot.com',
    measurementId: 'G-0GBKWQ7K7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQrDhQOdhDOQh87Cxo6gEpgBef9O66mFU',
    appId: '1:9980413148:android:955cbec55f4f35921a6019',
    messagingSenderId: '9980413148',
    projectId: 'protectora-555d4',
    storageBucket: 'protectora-555d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCltR0FOJyb9lluawmTS3gNglLgBGqWu3M',
    appId: '1:9980413148:ios:f593d58dfd62dec21a6019',
    messagingSenderId: '9980413148',
    projectId: 'protectora-555d4',
    storageBucket: 'protectora-555d4.appspot.com',
    iosBundleId: 'com.example.protectora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCltR0FOJyb9lluawmTS3gNglLgBGqWu3M',
    appId: '1:9980413148:ios:f593d58dfd62dec21a6019',
    messagingSenderId: '9980413148',
    projectId: 'protectora-555d4',
    storageBucket: 'protectora-555d4.appspot.com',
    iosBundleId: 'com.example.protectora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN4G_eenl95cZIQL2Uc2mvRTz6eNQuhAI',
    appId: '1:9980413148:web:82d79c6f1808b53c1a6019',
    messagingSenderId: '9980413148',
    projectId: 'protectora-555d4',
    authDomain: 'protectora-555d4.firebaseapp.com',
    storageBucket: 'protectora-555d4.appspot.com',
    measurementId: 'G-V78PQDMHX6',
  );
}
